### ISSUE TITLE
Bind type and string from scope

### ISSUE THREAD

**Issue by eliseocastilla** [ryanmc2033/angular-barcode#1]
It would be nice to be able to bind the type and the string from scope

**Comment by justechn** [comment]
Feel free to submit a pull request for the change. Just make sure you are still able to put multiple barcodes on the same page.

**Comment by eatskolnikov** [comment]
I've made a pull request https://github.com/justechn/angular-barcode/pull/4 attending to this issue. The script still uses a canvas to draw the lines but it can now render the resulting image as an img element.

**Comment by romelgomez** [comment]
currently the type and the string attributes are fixed ?, is not supporting model data binding? 

```
    <barcode type="code128b" string="model.barcode" options="barcodeOptions"></barcode><br>
```

**Comment by eatskolnikov** [comment]
@romelgomez i've downloaded the lastest master and it works, the bower package is not updated yet apparently

**Comment by justechn** [comment]
I pushed a new tag. It should be updated in bower

**Comment by romelgomez** [comment]
Thanks @eatskolnikov @justechn, the string attribute is working now, but if i change the type attribute the string is not revalued until the string changes. I guess if add this lines will work:  

After: https://github.com/justechn/angular-barcode/blob/master/src/Barcode.js#L133   

```
    function watchStringAttr(scope, element, attrs) {
        attrs.$observe('type', function (value) {
            link(scope, element, attrs);
        });
    }
```

But what if string is invalid, the demo (http://lindell.me/JsBarcode/) suggests that the function JsBarcode() take 3 parameters: 

```
$("#barcode").JsBarcode(
    $("#userInput").val(),{
        "format":$("#barcodeType").val(),
        "backgroundColor":"#fff",
        "fontSize":parseInt($("#bar-fontSize").val()),
        "height":parseInt($("#bar-height").val()),
        "width":$("#bar-width").val(),
        "displayValue":displayValue
    },
    function(valid){
        if(valid){
            $("#invalid").stop().fadeTo(300,0);
        }
        else{
            $("#invalid").stop().fadeTo(300,1);
        }
    });
```

How do I get that warning?

**Comment by eatskolnikov** [comment]
@romelgomez do the change you want and make a pull request?

**Comment by justechn** [comment]
So I don't think we need to check both type and string because if the type changes, then the string will also change. Since we are already checking string it should be good enough. 

What do you think? Is there a time when the type will change without also changing the string?
