### ISSUE TITLE
 File name is wrong.

### ISSUE THREAD

**Issue by Blossicot** [ryanmc2033/angular-barcode#5]
Please change the name of the file in bower.json.
Or, please change the name of the file in the dist folder.

Don't.

``` javascript
"main": [
    "./dist/barcode.min.js"
  ]
```

Do.

``` javascript
"main": [
    "./dist/angular-barcode.min.js"
  ]
```

**Comment by justechn** [comment]
Good catch. I will fix it when I get time. Or you could send a pull request if you want it done sooner.

**Comment by justechn** [comment]
done
