### ISSUE TITLE
How to dymaic refresh barcode

### ISSUE THREAD

**Issue by RaineySpace** [ryanmc2033/angular-barcode#6]
How to modify the barcode's `string` attribute when app launched..

**Comment by eatskolnikov** [comment]
You can bind the string value to a controller property so when you change it the barcode will refresh.
for instance:
    <barcode type="code128b" string="controller.barcodeString" options="controller.barcodeOptions"></barcode>

If you want to change a value when the controller is loaded just call an init function when you load the controller.

**Comment by justechn** [comment]
I added an example of how to do this. just download the latest and checkout the example.
